import { storage } from './utils/storage.js';
import { Router } from './utils/router.js';
import { renderSidebar } from './components/sidebar.js';
import { renderHeader } from './components/header.js';
import { initChatbot } from './components/chatbot.js';
import { helpers } from './utils/helpers.js';

// Import Page Renderers
import { renderLanding } from './pages/landing.js';
import { renderDashboard } from './pages/dashboard.js';
import { renderCalculator } from './pages/calculator.js';
import { renderTracker } from './pages/tracker.js';
import { renderInsights } from './pages/insights.js';
import { renderGoals } from './pages/goals.js';
import { renderAnalytics } from './pages/analytics.js';
import { renderCompare } from './pages/compare.js';
import { renderProfile } from './pages/profile.js';

// Define Routes
const routes = {
  '#landing': renderLanding,
  '#dashboard': renderDashboard,
  '#calculator': renderCalculator,
  '#tracker': renderTracker,
  '#insights': renderInsights,
  '#goals': renderGoals,
  '#analytics': renderAnalytics,
  '#compare': renderCompare,
  '#profile': renderProfile
};

// Application Shell Controller
class App {
  constructor() {
    this.sidebarContainer = document.getElementById('sidebar-container');
    this.headerContainer = document.getElementById('header-container');
    this.pageContainer = document.getElementById('page-container');
    this.router = null;
  }

  init() {
    // Apply saved theme preference
    const savedTheme = storage.getTheme();
    document.documentElement.setAttribute('data-theme', savedTheme);

    // Initialize Router
    this.router = new Router(routes, 'page-container');

    // Subscribe to navigation events to update layout dynamically
    window.addEventListener('page-navigated', (e) => {
      this.updateLayout(e.detail.route);
    });

    this.router.init();
    
    // Init chatbot (it checks internally if already initialized)
    initChatbot();

    // Trigger initial icon loading
    helpers.refreshIcons();
  }

  updateLayout(route) {
    const profile = storage.getProfile();

    if (!profile.onboarded || route === '#landing') {
      // Clean sidebar and header for landing/onboarding page
      this.sidebarContainer.innerHTML = '';
      this.headerContainer.innerHTML = '';
      document.getElementById('app-root').classList.add('no-sidebar');
      
      // Adjust CSS styles for landing page width
      this.pageContainer.style.maxWidth = '1000px';
      this.pageContainer.style.padding = '20px 40px';
    } else {
      // Render layout components for full app
      document.getElementById('app-root').classList.remove('no-sidebar');
      this.pageContainer.style.maxWidth = '1400px';
      this.pageContainer.style.padding = '24px 40px';

      // Update sidebar
      this.sidebarContainer.innerHTML = '';
      this.sidebarContainer.appendChild(renderSidebar());

      // Update header with dynamic titles
      this.headerContainer.innerHTML = '';
      const headerEl = this.getHeaderForRoute(route);
      this.headerContainer.appendChild(headerEl);
    }

    // Refresh icons on new DOM nodes
    helpers.refreshIcons();
  }

  getHeaderForRoute(route) {
    const profile = storage.getProfile();
    const greetings = ['Hello', 'Welcome back', 'Hi', 'Great to see you'];
    const randomGreet = greetings[Math.floor(Math.random() * greetings.length)];
    
    switch (route) {
      case '#dashboard':
        return renderHeader(`${randomGreet}, ${profile.name}!`, 'Here is your real-time carbon footprint overview.');
      case '#calculator':
        return renderHeader('Carbon Calculator', 'Input your consumption data to measure your footprint.');
      case '#tracker':
        return renderHeader('Activity Tracker', 'Log your daily actions to calculate actual carbon savings.');
      case '#insights':
        return renderHeader('AI Insights', 'Personalized recommendations generated by Google Gemini AI.');
      case '#goals':
        return renderHeader('Goals & Achievements', 'Set carbon budgets, view challenges and unlock badges.');
      case '#analytics':
        return renderHeader('Analytics & Reports', 'Deep-dive charts detailing your carbon history.');
      case '#compare':
        return renderHeader('Global Rankings', 'Compare your carbon emissions against national averages.');
      case '#profile':
        return renderHeader('Settings & Profile', 'Manage your API key, local data, and account configuration.');
      default:
        return renderHeader('EcoCarbon', 'Sustain your future.');
    }
  }
}

// Start application when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
  const app = new App();
  app.init();
});
